name: sage-binder-env

channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  # Required by the SageMath kernel in Jupyter
  - ipywidgets
  # Install the full distribution of SageMath.
  - sage=9.6
  # If you chose sagelib instead of sage above, you can add the required
  # features manually here, e.g., matplotlib-base for basic plotting, sympy for
  # symbolic computations, …. See the "run" section of
  # https://github.com/conda-forge/sage-feedstock/blob/main/recipe/meta.yaml
  # for the things that are included in "sage" but that might be missing from
  # "sagelib".
